---
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: ssh-key-collection
spec:
  credentials:
    - filename: ssh.key
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: ssh-key
        key: key
  requirements: |
    # multiple collections can be hosted in a single git repo
    ---
    collections:
      - name: acme.collection
        source: https://gitlab.com/janwillies/ansible-collection.git
        type: git
      # - name: acme.collection1
      #   source: https://gitlab.com/janwillies/ansible-collection.git#/collection1/
      #   type: git
      # - name: acme.collection2
      #   source: https://gitlab.com/janwillies/ansible-collection.git#/collection2/
      #   type: git
---
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: example-gitlab-collection
spec:
  forProvider:
    inventoryInline: |
      vm-1.vm
    playbookInline: |
      ---
      - name: Run a playbook using roles from different collections
        hosts: all
        roles:
          - acme.collection1.role1
          - acme.collection2.role2
    vars:
      ansible_ssh_user: ansible
      ansible_ssh_private_key_file: ./ssh.key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  providerConfigRef:
    name: ssh-key-collection