---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sshd-config
  namespace: vm
data:
  sshd_config: |
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    UsePAM no
    Subsystem	sftp	/usr/lib/openssh/sftp-server
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFWUlxiScNEHiZMn82a8qHOpsnH7cuFLZu2SyqMCfGt4 your_email@example.com