---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-1
  namespace: user-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible-editor
  namespace: user-1
subjects:
- kind: ServiceAccount
  name: user-1
  namespace: user-1
roleRef:
  kind: ClusterRole
  name: ansible-editor
  apiGroup: rbac.authorization.k8s.io